name: Auto Bump llama.cpp
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  auto-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check changes llama.cpp master HEAD and push update if any
        id: git-status
        run: |
            cd llama.cpp/
            git fetch origin
            git checkout master
            git reset --hard origin/master
            cd ../

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update llama.cpp
          title: Auto bump llama.cpp version
          body: Auto bump llama.cpp version
          branch: bump-llamacpp
          branch-suffix: timestamp
          labels: "type: chore"
          reviewers: tikikun
          assignees: vuonghoainam
          delete-branch: true
          add-paths	: "llama.cpp"
    
